[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hal"
version = "0.1.0"
description = "Agent evaluation harness with optional benchmark support"
requires-python = ">=3.9"
dependencies = [
    "datasets==3.2.0",
    "weave",
    "huggingface-hub==0.26.5",
    "python-dotenv",
    "setuptools>=48.0.0",
    "inspect_ai @ git+https://github.com/UKGovernmentBEIS/inspect_ai@4c189e53f30a06b740df2b2ce5b3aa2dd79c57ee",
    "inspect-evals @ git+https://github.com/UKGovernmentBEIS/inspect_evals@5341ed9e6b1af43d8534b1d3c310115f092f16bc",
    "azure-mgmt-compute>=29.1.0",
    "azure-mgmt-network>=25.1.0",
    "azure-mgmt-resource>=23.0.1",
    "azure-identity>=1.12.0",
    "paramiko",
    "tenacity>=8.2.0",
    "docker>=7.1.0",
    "cryptography>=42.0.0",
    "litellm==1.55.0",
    "boto3",
    "seaborn==0.13.2",
]

[project.optional-dependencies]

[project.scripts]
hal-eval = "hal.cli:main"
hal-upload = "hal.utils.upload:upload_results"
hal-decrypt = "hal.utils.decrypt:decrypt_cli"

[tool.setuptools]
packages = ["hal"]
